**NumPy** - **Element**-**wise** **Matrix** **Operations**


**Matrix** **Addition**

In [ ]:
import numpy as np
arr1 = np.array([[1,2],[3,6]])
arr2 = np.array([[1,2], [3,6]])
addition = np.add(arr1, arr2)
print(addition)

[[ 2  4]
 [ 6 12]]


**Matrix** **Subtraction**

In [ ]:
subtraction = np.subtract(arr1, arr2)
print(subtraction)

[[0 0]
 [0 0]]


**Matrix** **Multiplication**

In [ ]:
multiplication = np.multiply(arr1,arr2)
print(multiplication)

[[ 1  4]
 [ 9 36]]


In [ ]:
arr3 = np.array([ [1,2,3]])
arr4 = np.array([[1], [2], [3]])
arr3
arr4

array([[1],
       [2],
       [3]])

In [ ]:
multiplication = np.multiply(arr3,arr4)
print(multiplication)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [ ]:
import numpy as np

arr3 = np.array([[1, 2, 3]])

arr4 = np.array([[1],
                 [2],
                 [3]])

result = arr3 @ arr4
print(result)

[[14]]


**Matrix** **Division**

In [ ]:
div = arr3/arr4
print(div)

[[1.         2.         3.        ]
 [0.5        1.         1.5       ]
 [0.33333333 0.66666667 1.        ]]


In [ ]:
import numpy as np

A = np.array([[10, 20],
              [30, 40]])

B = np.array([[2, 4],
              [5, 8]])

result = A / B
print(result)

[[5. 5.]
 [6. 5.]]


**Scalar** **Operations**

In [ ]:
# Scalar
scaler = 2
result_add = A +2
print(result_add)

[[12 22]
 [32 42]]


In [ ]:
mut_add = A * 2
print(mut_add)

[[20 40]
 [60 80]]


In [ ]:
A = np.array([[10, 20],
              [30, 40]])
B = np.array([[1,2]])
added = A + B
added

array([[11, 22],
       [31, 42]])

**Linear** **Algebra** **in** **numpy**

In [ ]:
A = np.array([[2,1],[1,3]])
B = np.array([5,6])
x = np.linalg.solve(A,B)
x

array([1.8, 1.4])

In [1]:
import numpy as np

A = np.array([
    [1,  1, 2, 1, 1],
    [2, -1, 1, 3, 2],
    [3,  1, 2, 2, -1],
    [1, -1, 1, 2, 3],
    [1,  2, 3, 1, 1]
])


E = np.array([5, 8, 4, 10, 7])

x = np.linalg.solve(A, E)

print(x)

[-3.50279971e+15 -7.00559942e+15  7.00559942e+15  1.01851852e+00
 -3.50279971e+15]


In [ ]:
import numpy as np

X = np.array([
    [1, 1],
    [2, 1],
    [3, 1]
])

Y = np.array([2, 3, 5])

beta = np.linalg.inv(X.T @ X) @ X.T @ Y

print(beta)
print("Slope:", beta[0])
print("Intercept:", beta[1])
print("Intercept:", beta[1])


In [ ]:
import numpy as np

X = np.array([
    [1, 1],
    [2, 1],
    [3, 1]
])

Y = np.array([2, 3, 5])

beta = np.linalg.inv(X.T @ X) @ X.T @ Y

print(beta)
print("Slope:", beta[0])
print("Intercept:", beta[1])

**Determinants** **&** **Inverse**

In [ ]:
import numpy as np
A = np.array([[1,2],
              [4,5]])
det = np.linalg.det(A)
print("Determinant:", det)

In [ ]:
inv = np.linalg.inv(A)
print("Inverse Matrix:", inv)


Eigenvalues and Eigenvectors

In [1]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigen Valies:", eigenvalues)
print("Eigen Vector:", eigenvectors)


NameError: name 'np' is not defined

Singular Value
Decomposition (SVD)

In [ ]:
U,S,V = np.linalg.svd(A)
print("U matrix: \n", U)
print("Sigma values:", S)
print("V matrix:", V)