

**Numpy**



NumPy (short for Numerical Python) is a popular Python library used for scientific
computing and numerical operations

list = single dimension

Numpy = Multi-dimension.

 Numpy is a python library.

**Arrays** **in** **Numpy**


A NumPy array (ndarray) is a collection of elements of the same data type stored in a multidimensional structure.

In [ ]:
import numpy as np

**1D** **Array**

In [ ]:
arr_1d = np.array([1,2,3,4,5,6]) #1D array
arr_1d

array([1, 2, 3, 4, 5, 6])

**2D** **Array**

In [ ]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8]]) #2D array
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**3D** **Array**

In [ ]:

import numpy as np

array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

array_3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

**List** **Vs** **Numpy** **Array**

In [ ]:
# list vs numpy array

In [ ]:
py_list = [1,2,3]
print("Python list multiplication", py_list * 2)

Python list multiplication [1, 2, 3, 1, 2, 3]


In [ ]:
ny_array = np.array([1,2,3]) # element wise multiplication
print("Python list multiplication", ny_array * 2) # 2 is a scalar, we can perform the vector mul

Python list multiplication [2 4 6]


In [ ]:
import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List  operation time:", time.time()-start)



 List  operation time: 0.008796215057373047


In [ ]:
start = time.time()
np_array = np.arange(10000) * 2
print("\nList operation time:", time.time()-start)


List operation time: 0.000530242919921875


Numpy is faster in performance compared to list.

In [ ]:
lst = [1,2,3,4,5]
print(sum(lst))

15


In [ ]:
import numpy as np
np_add = np.sum(lst)
print(np_add)


15


what is rank?

Number of dimensions in an array is called rank.

In [ ]:
#Rank 0 (Scalar)
a = np.array(10)
a.ndim

0

In [ ]:
#Rank 1 (vector) #Rank1 is called vector
a = np.array([1,2,3,4])
a.ndim

1

In [ ]:
# Rank 2 (Matrix) Rank2 is called matrix
a = np.array([[1,2,3], [4,5,6]])
a.ndim # ndim gives rank

2

In [ ]:
a.shape # It gives rows and column

(2, 3)

Create 5*5 matrix and check the rank

In [ ]:
a = np.array([
    [[1,2,3,4,5], [2,3,4,5,6]],
    [[23,5,6,2,7],[4,6,7,8,0]],
    [[5,6,7,8,9],[1,2,7,58,8]],
    [[5,7,8,9,4],[3,52,7,8,9]],
    [[2,4,5,6,7],[2,1,5,6,7]]
    ])
a.ndim
a.shape

(5, 2, 5)

**np**.**zeros**() **and** **np**.**ones**()

np.zeros() and np.ones() are NumPy functions used to
create new arrays filled entirely with zeros (0) or ones (1).

In [ ]:
zeros = np.zeros((3,4))
print("Zero array: \n", zeros)

Zero array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones = np.ones((4,5))
print("Zero array: \n", ones)

Zero array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


1, 0 is maximum used in image and marking

In [ ]:
np.zeros(shape = (4,5), dtype = "int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape = (4,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.array([[1,2,3],
             [4,5,6]])
print(a.sum(axis=0)) # axis 0 = Column

[5 7 9]


In [ ]:
a = np.array([[1,2,3],
             [4,5,6]])
print(a.sum(axis=1)) # axis 1 = Row

[ 6 15]


In [ ]:
# Random array
random = np.random.random((2,3))
print("Random array: \n", random)

Random array: 
 [[0.30307287 0.26784654 0.31327371]
 [0.6816881  0.86833491 0.90344448]]


full() - creates an array with all elements initialized to same user-specified value.

In [ ]:
import numpy as np

arr = np.full((4, 5), fill_value=7)
print(arr)


[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
full = np.full((4,5), 9)
print(full)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


arange() - create sequences of numbers (like Python’s range() but more powerful).


In [ ]:
arr = np.arange(2,10,3)
arr

array([2, 5, 8])

np.linspace() - create evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(1, 5, 4, dtype = int)

array([1, 2, 3, 5])

In [ ]:
import numpy as np

arr = np.linspace(0, 10, 5, dtype = int)
print(arr)

[ 0  2  5  7 10]


In [ ]:
arr = np.linspace(0,10,4, dtype = int)
arr

array([ 0,  3,  6, 10])

np.diag() - create a diagonal matrix or extract diagonal elements from a matrix.

In [ ]:
#diag() - create diagonal matrix
arr = np.diag([1,2,3])
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

np.eye() - create an identity matrix (a matrix with 1s on the main diagonal and 0s elsewhere).

In [ ]:
#eye() - create matrix with ones on diagonal
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


identity() - create an identity matrix

In [ ]:
# identity() - create identity matrix
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Difference between eye() and identity().

np.identity() → creates only a square identity matrix

np.eye() → more flexible, can create rectangular matrices and shifted diagonals

Identity matrix is always square and eye() can be implemented in rectangle

In [ ]:
# Always have to be square matrix. That's way it shows error.
arr = np.identity(3,5)
print(arr)

TypeError: Cannot interpret '5' as a data type

random.rand() is used to generate random numbers between 0 and 1 (uniform distribution)

In [ ]:
# Create a array of random numbers
arr = np.random.rand(2,3)
arr

array([[0.38533832, 0.62474803, 0.25673772],
       [0.22618879, 0.0670136 , 0.56579752]])