**NumPy** **Array** **Properties** **and** **Methods**

In [ ]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6.5]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("Dtype:", arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
Dtype: float64


In [ ]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,"data"]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("Dtype:", arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
Dtype: <U21


In [ ]:
import numpy as np
arr = np.array(['apple', 'banana', 'watermelon'])
print(arr.dtype)

<U10


Important Topic

Transpose of Matrix

 **reshape**() is used to change the shape (dimensions) of an array without changing its data.

In [ ]:
# Array Reshaping
import numpy as np
arr = np.arange(12)
print("Original array", arr)


Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
reshaped = arr.reshape(3,4) # reshape le tuple ma value linxa
print("Reshaped:", reshaped)

Reshaped: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
reshaped = arr.reshape(2,6) # reshape le tuple ma value linxa
print("Reshaped:", reshaped)

Reshaped: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


Reshape in 2D

In [ ]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6]])

In [ ]:
reshaped_2D = arr.reshape((3,2))
print("Reshaped:", reshaped_2D)

Reshaped: [[1 2]
 [3 4]
 [5 6]]


**flatten**() is used to convert a multi-dimensional array into a 1D (one-dimensional) array.

In [ ]:
# Copy the original of array
flattened = reshaped.flatten()
print("Flattened:", flattened)

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


ravel() is used to flatten a multi-dimensional array into a 1D array, similar to flatten(), but with an important difference.

✅ **Key** **Difference**

ravel() → returns a view (if possible)
flatten() → always returns a copy


In [ ]:
# View the original of array
raveled = reshaped.ravel()
print("Ravelled:",raveled)

Ravelled: [ 0  1  2  3  4  5  6  7  8  9 10 11]


**Transpose** **of** **Matrix**

In [ ]:
# Transpose
print("Original:", reshaped)
print("@@@@@@@@")
transpose = reshaped.T
print("\n Transposed Array:", transpose)

Original: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
@@@@@@@@

 Transposed Array: [[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [ ]:
# numpy array operation

**Indexing** **&** **Slicing**

In [ ]:
# indexing and slicing

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing:", arr[2:7])

Basic Slicing: [3 4 5 6 7]


In [ ]:
arr = np.array([[1,2,3],
                [3,5,9],
                [4,5,6]])
print("Basic Slicing:", arr[0:2, 1:3])
print(arr[1,:])

Basic Slicing: [[2 3]
 [5 9]]
[3 5 9]


In [ ]:
print(arr[:2, :])

[[1 2 3]
 [3 5 9]]


In [ ]:
# Sub Matrix
arr = np.array([[1,2,3],
                [3,5,9],
                [4,5,6]])
print(arr[0:2, 1:3])

[[2 3]
 [5 9]]


In [ ]:
# Entire Second Row
print(arr[1,:])

[3 5 9]


In [ ]:
# Last Two Column
print(arr[:, :2])

[[1 2]
 [3 5]
 [4 5]]


In [ ]:
#Reverse
print(arr[::-1])

[[4 5 6]
 [3 5 9]
 [1 2 3]]


In [ ]:
# Reverse Column
print(arr[:, ::-1])

[[3 2 1]
 [9 5 3]
 [6 5 4]]


**Sorting** **in** **Numpy**

In [ ]:
#Sorting
unsorted = np.array([2,3,4,5,6,7,1,0,9])
print(np.sort(unsorted))

[0 1 2 3 4 5 6 7 9]


In [ ]:
arr_2D_unsorted = np.array([[3,1], [1,2], [3,2]])
print("Sorted 2D by Column:", np.sort(arr_2D_unsorted, axis = 1))

Sorted 2D by Column: [[1 3]
 [1 2]
 [2 3]]


In [ ]:
arr_2D_unsorted = np.array([[3,1], [1,2], [3,2]])
print("Sorted 2D by Rows:", np.sort(arr_2D_unsorted, axis = 0))

Sorted 2D by Rows: [[1 1]
 [3 2]
 [3 2]]


**Filter** **in** **Numpy**

In [ ]:
# Filter
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_number = numbers[numbers % 2 == 0]
print(even_number)

[2 4 6 8]


In [ ]:
# Filter with mask
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [6 7 8 9]


In [ ]:
numbers[numbers>5] = 1000
print(numbers)

[   1    2    3    4    5 1000 1000 1000 1000]


In [ ]:
# index
numbers = np.array([1,2,3,4,5,6,7,8,9])
indices = [0,2,4]
print(numbers[indices])

[1 3 5]


**Where**() **in** **Numpy**

In [ ]:
#np.where()
where_result = np.where(numbers>5)
print(where_result) # Gives index position
print("Numner where", numbers[where_result])

(array([5, 6, 7, 8]),)
Numner where [6 7 8 9]


**Conditional** **in** **Numpy**

In [ ]:
# Conditional
condition_array = np.where(numbers>5, numbers*4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36]


**Adding** **and** **Removing** **Data**

In [ ]:
# Adding and removing data
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
adding = np.add(arr1, arr2)
combine = np.concatenate((arr1,arr2))
print(adding)
print(combine)

[ 6  8 10 12]
[1 2 3 4 5 6 7 8]


In [ ]:
arr1.shape

(4,)

In [ ]:
arr2.shape

(4,)

In [ ]:
arr1.shape == arr2.shape # Check matrix Compatibility

True

**vstack**() **in** **Numpy**

In [ ]:
# Create 2*2 matrix and add one row
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
print("Original \n", original)
print("__________\n")
add_row = np.vstack((original, new_row))
print("Add Row:\n", add_row)

Original 
 [[1 2]
 [3 4]]
__________

Add Row:
 [[1 2]
 [3 4]
 [5 6]]


**hstack** **in** **Numpy**

In [ ]:
# Add column
new_column = np.array([[7], [8]])
added_column = np.hstack((original, new_column))
print("Add Column\n:", added_column)

Add Column
: [[1 2 7]
 [3 4 8]]


**Delete** **in** **Numpy**

In [ ]:
# Delete
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print(deleted)

[1 2 4 5]
